image: ubuntu:22.04

build_linux:
  stage: build
  only:
    - hestina

  before_script:
    - apt update
    - apt install -y gcc-12 g++-12
    - apt install -y cmake ninja ccache
    - mkdir -p .build

  script:
    - cd .build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -S.. -B. -G Ninja
    - cmake --build . --config Debug --target all

  artifacts:
    paths:
      - .build
    expire_in: 1d

test_linux:
  stage: test
  only:
    - hestina

  script:
    - ctest -C Debug -T test --output-on-failure
