set(LIB_NAME usb_cap)
set(LIB_NAMESPACE ${LIB_NAME})

add_library(${LIB_NAME} SHARED IMPORTED)
add_library(${LIB_NAMESPACE}::${LIB_NAME} ALIAS ${LIB_NAME})

set_target_properties(${LIB_NAME} PROPERTIES
    IMPORTED_LOCATION $ENV{HOMEDRIVE}$ENV{HOMEPATH}/Desktop/USB/USBcap.dll
    IMPORTED_IMPLIB $ENV{HOMEDRIVE}$ENV{HOMEPATH}/Desktop/USB/USBcap.lib
    INTERFACE_INCLUDE_DIRECTORIES ${CMAKE_CURRENT_SOURCE_DIR})
