set(LIB_NAME usb_cap)
set(LIB_NAMESPACE ${LIB_NAME})

add_library(${LIB_NAME} SHARED IMPORTED)
add_library(${LIB_NAMESPACE}::${LIB_NAME} ALIAS ${LIB_NAME})

string(REPLACE "\\" "/" PREFIX $ENV{HOMEDRIVE}$ENV{HOMEPATH})
set_target_properties(${LIB_NAME} PROPERTIES
    IMPORTED_LOCATION ${PREFIX}/Desktop/USB/USBcap.dll
    IMPORTED_IMPLIB ${PREFIX}/Desktop/USB/USBcap.lib
    INTERFACE_INCLUDE_DIRECTORIES ${CMAKE_CURRENT_SOURCE_DIR})

install(IMPORTED_RUNTIME_ARTIFACTS usb_cap
    DESTINATION bin)
