name: Windows Server 2022

on:
  push:
    branches: [leetcode-cn]

jobs:
  build_on_windows:
    runs-on: windows-latest

    strategy:
      matrix:
        mode: [Debug, Release]
        arch: [amd64, x86]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Download and install Boost
        uses: MarkusJx/install-boost@v2.4.4
        id: install-boost
        with:
          boost_version: 1.78.0
          platform_version: 2022
          toolset: msvc
          link: shared

      - name: Install Qt
        uses: jurplel/install-qt-action@v3.2.1
        with:
          version: 5.15.2

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.0
        with:
          arch: ${{ matrix.arch }}

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -G Ninja -B ${{github.workspace}}/.build

      - name: Build
        run: cmake --build ${{github.workspace}}/.build --config ${{ matrix.mode }}

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Test
        working-directory: ${{github.workspace}}/.build
        run: ctest -C ${{matrix.mode}} -j ${{ steps.cpu-cores.outputs.count }} -V --output-on-failure --tests-regex leetcode-cn* --exclude-regex leetcode-cn_primeval.1117
